In [88]:
import numpy as np
import pandas as pd

In [89]:
a=np.arange(15)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [90]:
a.shape

(15,)

In [91]:
a.size

15

In [92]:
a.dtype

dtype('int32')

In [93]:
a.ndim

1

In [94]:
a.itemsize#no of bytes

4

In [95]:
type(a)

numpy.ndarray

In [96]:
a=np.arange(15).reshape(5,3)
a

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [97]:
a.size

15

In [98]:
a.shape

(5, 3)

In [99]:
a.ndim

2

In [100]:
a.dtype

dtype('int32')

In [101]:
a=np.array([1,2,3.0])
a

array([1., 2., 3.])

In [102]:
a.dtype

dtype('float64')

In [103]:
a=np.array([1,2,3.0,0],dtype="complex")
a

array([1.+0.j, 2.+0.j, 3.+0.j, 0.+0.j])

In [104]:
a=np.array([1,2,3.0,0],dtype="bool")
a

array([ True,  True,  True, False])

In [105]:
a=np.array([[1,2,3.0,0],[4,7,5,5]])
a

array([[1., 2., 3., 0.],
       [4., 7., 5., 5.]])

In [106]:
a.ndim

2

In [107]:
a.shape

(2, 4)

In [108]:
a=np.array((3,4,5))
a

array([3, 4, 5])

In [109]:
np.ones((2,3),dtype=np.int8)

array([[1, 1, 1],
       [1, 1, 1]], dtype=int8)

In [110]:
np.zeros((2,3),dtype=np.int8)

array([[0, 0, 0],
       [0, 0, 0]], dtype=int8)

In [111]:
np.empty((2,3),dtype=np.int8)

array([[57,  5,  0],
       [ 0, 32, 32]], dtype=int8)

In [112]:
np.arange(10,45,5)

array([10, 15, 20, 25, 30, 35, 40])

In [116]:
np.arange(10,45,0.85).reshape(-1,7)

array([[10.  , 10.85, 11.7 , 12.55, 13.4 , 14.25, 15.1 ],
       [15.95, 16.8 , 17.65, 18.5 , 19.35, 20.2 , 21.05],
       [21.9 , 22.75, 23.6 , 24.45, 25.3 , 26.15, 27.  ],
       [27.85, 28.7 , 29.55, 30.4 , 31.25, 32.1 , 32.95],
       [33.8 , 34.65, 35.5 , 36.35, 37.2 , 38.05, 38.9 ],
       [39.75, 40.6 , 41.45, 42.3 , 43.15, 44.  , 44.85]])

In [224]:
np.arange(10,45,0.85).reshape(3,2,7)

array([[[10.  , 10.85, 11.7 , 12.55, 13.4 , 14.25, 15.1 ],
        [15.95, 16.8 , 17.65, 18.5 , 19.35, 20.2 , 21.05]],

       [[21.9 , 22.75, 23.6 , 24.45, 25.3 , 26.15, 27.  ],
        [27.85, 28.7 , 29.55, 30.4 , 31.25, 32.1 , 32.95]],

       [[33.8 , 34.65, 35.5 , 36.35, 37.2 , 38.05, 38.9 ],
        [39.75, 40.6 , 41.45, 42.3 , 43.15, 44.  , 44.85]]])

In [225]:
np.linspace(0,2,9)

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [226]:
np.linspace(0,2,9,endpoint=False)

array([0.        , 0.22222222, 0.44444444, 0.66666667, 0.88888889,
       1.11111111, 1.33333333, 1.55555556, 1.77777778])

In [227]:
np.linspace(0,2,9,endpoint=False,retstep=True)

(array([0.        , 0.22222222, 0.44444444, 0.66666667, 0.88888889,
        1.11111111, 1.33333333, 1.55555556, 1.77777778]),
 0.2222222222222222)

In [228]:
from numpy import pi
np.linspace(0,2,9)
x=np.linspace(0,2,100)
np.tan(x)

array([ 0.00000000e+00,  2.02047689e-02,  4.04260411e-02,  6.06803737e-02,
        8.09844322e-02,  1.01355046e-01,  1.21809262e-01,  1.42364408e-01,
        1.63038147e-01,  1.83848540e-01,  2.04814115e-01,  2.25953931e-01,
        2.47287654e-01,  2.68835631e-01,  2.90618973e-01,  3.12659645e-01,
        3.34980558e-01,  3.57605675e-01,  3.80560121e-01,  4.03870300e-01,
        4.27564037e-01,  4.51670714e-01,  4.76221433e-01,  5.01249194e-01,
        5.26789085e-01,  5.52878500e-01,  5.79557378e-01,  6.06868469e-01,
        6.34857632e-01,  6.63574168e-01,  6.93071194e-01,  7.23406066e-01,
        7.54640856e-01,  7.86842889e-01,  8.20085358e-01,  8.54448019e-01,
        8.90017992e-01,  9.26890672e-01,  9.65170785e-01,  1.00497360e+00,
        1.04642632e+00,  1.08966976e+00,  1.13486021e+00,  1.18217169e+00,
        1.23179859e+00,  1.28395879e+00,  1.33889736e+00,  1.39689098e+00,
        1.45825328e+00,  1.52334128e+00,  1.59256316e+00,  1.66638792e+00,
        1.74535708e+00,  

In [229]:
np.tan(45)

1.6197751905438615

In [230]:
a=np.arange(5)
a

array([0, 1, 2, 3, 4])

In [231]:
b=np.array([2,3,45,6,7])
b

array([ 2,  3, 45,  6,  7])

In [232]:
c=a-b
c

array([ -2,  -2, -43,  -3,  -3])

In [233]:
d=a+b
d

array([ 2,  4, 47,  9, 11])

In [234]:
a**2

array([ 0,  1,  4,  9, 16], dtype=int32)

In [235]:
m=a*b
m

array([ 0,  3, 90, 18, 28])

In [236]:
b<30

array([ True,  True, False,  True,  True])

In [237]:
a=np.ones((2,2))
a

array([[1., 1.],
       [1., 1.]])

In [238]:
b=np.array([[2,3],[5,6]])
b

array([[2, 3],
       [5, 6]])

In [239]:
c=a+b
c

array([[3., 4.],
       [6., 7.]])

In [240]:
d=a-b
d

array([[-1., -2.],
       [-4., -5.]])

In [241]:
m=a*b
m

array([[2., 3.],
       [5., 6.]])

In [242]:
x=a@b
x

array([[7., 9.],
       [7., 9.]])

In [243]:
y=a.dot(b)
y

array([[7., 9.],
       [7., 9.]])

In [244]:
from numpy import random

In [250]:
df=pd.DataFrame(np.random.randn(3,2))#standard normal distribution
df.describe()

0         1
count  3.000000  3.000000
mean  -0.667263  0.866340
std    0.278715  0.615286
min   -0.986597  0.156076
25%   -0.764430  0.681342
50%   -0.542264  1.206608
75%   -0.507596  1.221472
max   -0.472929  1.236337

In [254]:
np.random.randint(3,high=9,size=10)#randf

array([6, 7, 4, 3, 7, 4, 5, 4, 5, 5])

In [256]:
np.random.random_integers(3,size=18)

C:\Users\91829\AppData\Local\Temp/ipykernel_16032/584448564.py:1: DeprecationWarning: This function is deprecated. Please call randint(1, 3 + 1) instead
  np.random.random_integers(3,size=18)


array([1, 2, 3, 3, 3, 1, 2, 3, 3, 1, 1, 1, 3, 2, 3, 3, 3, 3])

In [288]:
np.random.random_sample(5)

array([0.51230071, 0.8676505 , 0.7510143 , 0.22889659, 0.46773627])

In [351]:
a=np.random.random(12)
print(a)
a.sum()
a.min()
a.max()

[0.21727576 0.56022994 0.4102154  0.84941208 0.04209711 0.56188716
 0.8256372  0.06369897 0.6382048  0.50119001 0.12225362 0.22060307]


0.8494120829680231

In [347]:
a1=np.arange(1,7)
np.random.shuffle(a1)
print(a1)

[5 1 6 4 3 2]


In [358]:
b=np.random.randint(1,12,size=12).reshape(4,3)
b

array([[ 4,  5, 11],
       [10,  7,  4],
       [ 4,  8, 11],
       [ 6,  3, 11]])

In [361]:
b.sum(axis=1)

array([20, 21, 23, 20])

In [364]:
b.min(axis=0)

array([4, 3, 4])

In [366]:
b.cumsum(axis=0)

array([[ 4,  5, 11],
       [14, 12, 15],
       [18, 20, 26],
       [24, 23, 37]], dtype=int32)

# universal functions--ufuncs

In [3]:
l1=[1,2,34,5]
l2=[3,4,5,6]
z=[]
for i, j in zip(l1,l2):
    z.append(i+j)
z

[4, 6, 39, 11]

In [4]:
import numpy as np

In [10]:
l1=[1,2,34,5]
l2=[3,4,5,6]
z=np.add(l1,l2)
z
type(np.add)

numpy.ufunc

In [13]:
def xyz(x,y):
    return x+y

xyz=np.frompyfunc(xyz,2,1)
print(xyz(l1,l2))


[4 6 39 11]


In [14]:
type(np.concatenate)

function

In [15]:
# simple arithmetic operations
z=np.add(l1,l2)
z

array([ 4,  6, 39, 11])

In [16]:
z=np.subtract(l1,l2)
z

array([-2, -2, 29, -1])

In [17]:
z=np.multiply(l1,l2)
z

array([  3,   8, 170,  30])

In [19]:
z=np.divide(l1,l2)
z

array([0.33333333, 0.5       , 6.8       , 0.83333333])

In [20]:
z=np.power(l1,l2)
z

array([       1,       16, 45435424,    15625], dtype=int32)

In [22]:
l1=[1,2,34,5]
l2=[3,4,5,6]
z=np.mod(l1,l2)
z

array([1, 2, 4, 5], dtype=int32)

In [23]:
l1=[1,2,34,5]
l2=[3,4,5,6]
z=np.remainder(l1,l2)
z

array([1, 2, 4, 5], dtype=int32)

In [25]:
z=np.divmod(l1,l2)
z

(array([0, 0, 6, 0], dtype=int32), array([1, 2, 4, 5], dtype=int32))

In [29]:
l1=[-1,-3,0,-9]
z=np.absolute(l1)
z

array([1, 3, 0, 9])

# roundingDecimals

In [30]:
#TRUNCATION
a=np.trunc([-3.6667,1.2345])
a

array([-3.,  1.])

In [31]:
a=np.fix([-3.6667,1.2345])
a

array([-3.,  1.])

In [32]:
a=np.around([-3.6667,1.2345])
a

array([-4.,  1.])

In [33]:
a=np.floor([-3.6667,1.2345])
a

array([-4.,  1.])

In [34]:
a=np.ceil([-3.6667,1.2345])
a

array([-3.,  2.])

#logspace

In [38]:
a=np.logspace(2,3)
a

array([ 100.        ,  104.81131342,  109.8541142 ,  115.13953993,
        120.67926406,  126.48552169,  132.57113656,  138.94954944,
        145.63484775,  152.64179672,  159.98587196,  167.68329368,
        175.75106249,  184.20699693,  193.06977289,  202.35896477,
        212.09508879,  222.29964825,  232.99518105,  244.20530945,
        255.95479227,  268.26957953,  281.1768698 ,  294.70517026,
        308.88435965,  323.74575428,  339.32217719,  355.64803062,
        372.75937203,  390.69399371,  409.49150624,  429.19342601,
        449.8432669 ,  471.48663635,  494.17133613,  517.94746792,
        542.86754393,  568.9866029 ,  596.36233166,  625.05519253,
        655.12855686,  686.648845  ,  719.685673  ,  754.31200634,
        790.60432109,  828.64277285,  868.51137375,  910.29817799,
        954.09547635, 1000.        ])

In [39]:
b=np.log10(a)
b

array([2.        , 2.02040816, 2.04081633, 2.06122449, 2.08163265,
       2.10204082, 2.12244898, 2.14285714, 2.16326531, 2.18367347,
       2.20408163, 2.2244898 , 2.24489796, 2.26530612, 2.28571429,
       2.30612245, 2.32653061, 2.34693878, 2.36734694, 2.3877551 ,
       2.40816327, 2.42857143, 2.44897959, 2.46938776, 2.48979592,
       2.51020408, 2.53061224, 2.55102041, 2.57142857, 2.59183673,
       2.6122449 , 2.63265306, 2.65306122, 2.67346939, 2.69387755,
       2.71428571, 2.73469388, 2.75510204, 2.7755102 , 2.79591837,
       2.81632653, 2.83673469, 2.85714286, 2.87755102, 2.89795918,
       2.91836735, 2.93877551, 2.95918367, 2.97959184, 3.        ])

In [43]:
a=np.arange(1,10)
b=np.log(a)
b

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 1.94591015, 2.07944154, 2.19722458])

In [45]:
from math import log
import numpy as np
nplog=np.frompyfunc(log,2,1)
print(nplog(100,5))

2.8613531161467867


In [51]:
l1=[1,2,34,5]
l2=[3,4,5,6]
n=np.sum([l1,l2],axis=1)
n

array([42, 18])

In [52]:
np.cumsum(l1)

array([ 1,  3, 37, 42], dtype=int32)

In [64]:
####practise question
l1=[ 8,5,7,10,15,21,4,5,8,8,8,9]
t=np.sum(l1)
mean=t/len(l1)
mean

9.0

In [65]:
#median
l1.sort()
l=len(l1)
if (l%2==0):
    i=l//2
    med=(l1[i]+l1[i-1])/2
else:
    i=l//2
    med=l1[i]
print(med)  

8.0


In [76]:
l2=[]
count=[]
c=0
for i in l1:
    if i not in l2:
        l2.append(i)
        for j in range(len(l1)):
            if(i==l1[j]):
                c+=1;
        count.append(c)
        c=0

a=np.array([l2,count])
b=a.argmax(axis=1)
l2[b[1]]
#l1=[ 8,5,7,10,15,21,4,5,8,8,8,9]  

8

In [87]:
import numpy as np
l1=[ 8,5,7,10,15,21,4,5,8,8,8,9]  
x=np.array(l1)
val,count=np.unique(x,return_counts=True)
y=np.argwhere(count==np.max(count))
print(val[y].flatten().tolist())

print(np.max(count))

[8]
4


In [129]:
import numpy as np
a=np.array([8,5,7,10])
b=np.array([3,4,1,2])

x=np.prod([a,b],axis=None)
x

67200

In [130]:
x=np.cumprod(a)
x

array([   8,   40,  280, 2800], dtype=int32)

In [133]:
x=np.diff(a,n=2)
x

array([5, 1])

In [137]:
n1=4
n2=6
x=np.lcm(n1,n2)
x
y=np.gcd(n1,n2)
y

2

In [138]:
a=np.array([8,5,7,10])
x=np.lcm.reduce(a)
x
y=np.gcd.reduce(a)
y

1

#set operations

In [139]:
l1=[1,23,3,5,5,2,1,1]
s=set(l1)
s

{1, 2, 3, 5, 23}

In [141]:
l1=[1,23,3,5,5,2,1,1]
a=np.array(l1)
x=np.unique(a)
x

array([ 1,  2,  3,  5, 23])

In [152]:
l1=[1,23,3,5,5,2,1,1]
a=np.array(l1)
l2=[3,4,56,78,1,2,90]
b=np.array(l2)
new=np.union1d(a,b)
new
inter=np.intersect1d(a,b)
inter
d=np.setdiff1d(b,a)
d
sd=np.setxor1d(b,a)
sd

array([ 4,  5, 23, 56, 78, 90])

In [168]:
arr=np.arange(10,45,0.85).reshape(-1,7)
arr

array([[10.  , 10.85, 11.7 , 12.55, 13.4 , 14.25, 15.1 ],
       [15.95, 16.8 , 17.65, 18.5 , 19.35, 20.2 , 21.05],
       [21.9 , 22.75, 23.6 , 24.45, 25.3 , 26.15, 27.  ],
       [27.85, 28.7 , 29.55, 30.4 , 31.25, 32.1 , 32.95],
       [33.8 , 34.65, 35.5 , 36.35, 37.2 , 38.05, 38.9 ],
       [39.75, 40.6 , 41.45, 42.3 , 43.15, 44.  , 44.85]])

In [169]:
arr.ndim


2

In [170]:
arr.shape

(6, 7)

In [171]:
for i in range(7):
    print(arr[0][i])

10.0
10.85
11.7
12.549999999999999
13.399999999999999
14.249999999999998
15.099999999999998


In [172]:
arr[1]

array([15.95, 16.8 , 17.65, 18.5 , 19.35, 20.2 , 21.05])

In [173]:
arr[4]

array([33.8 , 34.65, 35.5 , 36.35, 37.2 , 38.05, 38.9 ])

In [175]:
arr[(-3,-2)]

32.099999999999994

In [162]:
arr[1]+arr[4]

array([49.75, 51.45, 53.15, 54.85, 56.55, 58.25, 59.95])

In [164]:
arr[(2,3)]

24.449999999999996

In [165]:
arr=np.arange(10,45,0.85).reshape(2,-1,7)
arr

array([[[10.  , 10.85, 11.7 , 12.55, 13.4 , 14.25, 15.1 ],
        [15.95, 16.8 , 17.65, 18.5 , 19.35, 20.2 , 21.05],
        [21.9 , 22.75, 23.6 , 24.45, 25.3 , 26.15, 27.  ]],

       [[27.85, 28.7 , 29.55, 30.4 , 31.25, 32.1 , 32.95],
        [33.8 , 34.65, 35.5 , 36.35, 37.2 , 38.05, 38.9 ],
        [39.75, 40.6 , 41.45, 42.3 , 43.15, 44.  , 44.85]]])

In [166]:
arr[(1,2,3)]

42.29999999999998

In [176]:
arr=np.arange(10,45,0.85).reshape(-1,7)
arr

array([[10.  , 10.85, 11.7 , 12.55, 13.4 , 14.25, 15.1 ],
       [15.95, 16.8 , 17.65, 18.5 , 19.35, 20.2 , 21.05],
       [21.9 , 22.75, 23.6 , 24.45, 25.3 , 26.15, 27.  ],
       [27.85, 28.7 , 29.55, 30.4 , 31.25, 32.1 , 32.95],
       [33.8 , 34.65, 35.5 , 36.35, 37.2 , 38.05, 38.9 ],
       [39.75, 40.6 , 41.45, 42.3 , 43.15, 44.  , 44.85]])

In [177]:
arr[4:]#entire 4 and 5 row

array([[33.8 , 34.65, 35.5 , 36.35, 37.2 , 38.05, 38.9 ],
       [39.75, 40.6 , 41.45, 42.3 , 43.15, 44.  , 44.85]])

In [178]:
arr[:4]#0,1,2,3 rows

array([[10.  , 10.85, 11.7 , 12.55, 13.4 , 14.25, 15.1 ],
       [15.95, 16.8 , 17.65, 18.5 , 19.35, 20.2 , 21.05],
       [21.9 , 22.75, 23.6 , 24.45, 25.3 , 26.15, 27.  ],
       [27.85, 28.7 , 29.55, 30.4 , 31.25, 32.1 , 32.95]])

In [183]:
arr[1,:2]

array([15.95, 16.8 ])

In [184]:
arr[2,3:]

array([24.45, 25.3 , 26.15, 27.  ])

In [185]:
arr[0:2,1:4]

array([[10.85, 11.7 , 12.55],
       [16.8 , 17.65, 18.5 ]])

In [189]:
a=np.array(['sachin','virat','yuvraj','234567890'])
a.dtype

dtype('<U9')

In [192]:
#shallow copy
x=np.array([1,2,3])
y=x
y[0]=56
y
x

array([56,  2,  3])

In [196]:
#deepcopy
z=np.copy(x)
z
z[0]=23
z

array([23,  2,  3])

In [197]:
x

array([56,  2,  3])

In [200]:
#FUNCTIONS
np.fromfunction(lambda i,j,k:i+j+k,(3,3,3),dtype='int32')

array([[[0, 1, 2],
        [1, 2, 3],
        [2, 3, 4]],

       [[1, 2, 3],
        [2, 3, 4],
        [3, 4, 5]],

       [[2, 3, 4],
        [3, 4, 5],
        [4, 5, 6]]])

In [201]:
a=np.mat(np.fromfunction(lambda i,j:i+j,(3,3),dtype='int32'))

matrix([[0, 1, 2],
        [1, 2, 3],
        [2, 3, 4]])

In [208]:
3*5+np.eye(4)

array([[16., 15., 15., 15.],
       [15., 16., 15., 15.],
       [15., 15., 16., 15.],
       [15., 15., 15., 16.]])

In [206]:
np.diag([1,2,3,4,56])

array([[ 1,  0,  0,  0,  0],
       [ 0,  2,  0,  0,  0],
       [ 0,  0,  3,  0,  0],
       [ 0,  0,  0,  4,  0],
       [ 0,  0,  0,  0, 56]])

In [215]:
a=np.matrix('1,2;3,4')
a

matrix([[1, 2],
        [3, 4]])

In [216]:
type(a)

numpy.matrix

In [217]:
a.A

array([[1, 2],
       [3, 4]])

In [218]:
a.A1

array([1, 2, 3, 4])

In [220]:
a.H#transpose---r to c and c to row

matrix([[1, 3],
        [2, 4]])

In [221]:
a.I#multiplicative inverse

matrix([[-2. ,  1. ],
        [ 1.5, -0.5]])

In [222]:
a.T

matrix([[1, 3],
        [2, 4]])

In [235]:
x=np.matrix(np.arange(12).reshape(3,4))
x

matrix([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [236]:
y=x[0]
y

matrix([[0, 1, 2, 3]])

In [227]:
x==y

matrix([[ True,  True,  True,  True],
        [False, False, False, False],
        [False, False, False, False]])

In [234]:
(x==y).any()

True

In [232]:
(x==y).any(0)

matrix([[ True,  True,  True,  True]])

In [233]:
(x==y).any(1)

matrix([[ True],
        [False],
        [False]])

In [237]:
x.argmax()

11

In [240]:
x.argmax(1)

matrix([[3],
        [3],
        [3]], dtype=int64)

In [241]:
x.argsort()

matrix([[0, 1, 2, 3],
        [0, 1, 2, 3],
        [0, 1, 2, 3]], dtype=int64)

In [250]:
np.diagflat([[1,2],[3,4]],k=-2)

array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 0],
       [0, 2, 0, 0, 0, 0],
       [0, 0, 3, 0, 0, 0],
       [0, 0, 0, 4, 0, 0]])

In [256]:
np.tri(3,5,-1)

array([[0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [1., 1., 0., 0., 0.]])

In [260]:
np.triu(x,1)

array([[ 0,  1,  2,  3],
       [ 0,  0,  6,  7],
       [ 0,  0,  0, 11]])

In [308]:
import random
random.seed(2)
print(random.randint(1,6))
random.seed(3)
print(random.randint(1,6))
random.seed(1)
print(random.randint(1,6))

1
2
2


In [310]:
print(random.seed(2))

None


In [ ]:
random.seed(2)
